[font]
size = 15

[font.normal]
family = "Iosevka"
style = "Light"
[font.bold]
style = "Medium"
[font.italic]
style = "Light Italic"
[font.offset]
x = 1

[window]
opacity = 0.7

[shell]
program = "/opt/homebrew/bin/fish"
